version: '3.3'
services:
    mongo:
        container_name: bookstore-mongodb
        image: mongo
        ports:
            - '27017:27017'
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo
            - MONGO_INITDB_DATABASE=bookstore
            - MONGO_BOOKSTORE_USER=bookstore
            - MONGO_BOOKSTORE_PASSWORD=bookstore
        networks:
            - bookstore-net
        volumes: 
            - ./utils/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    bookstore:
        container_name: bookstore_api
        image: bookstore:v1
        ports: 
            - 8000:80
        environment:
            - MONGO_HOST=bookstore-mongodb
            - MONGO_PORT=27017
            - MONGO_USERNAME=bookstore
            - MONGO_PASSWORD=bookstore
            - MONGO_DATABASE=bookstore
        networks:
            - bookstore-net

networks: 
  bookstore-net: {}